name: test
on:
- pull_request
jobs:
  fluent-sqlite-driver_bionic:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - run: apt update -y; apt install -y libsqlite3-dev
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
  fluent-sqlite-driver_xenial:
    container: 
      image: vapor/swift:5.2-xenial
    runs-on: ubuntu-latest
    steps:
    - run: apt update -y; apt install -y libsqlite3-dev
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
